### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by TRaMeLL** [kov-serg/ai-extension#1]
1. Не правильно определяется тип процессора (x32, x64), Windows 10 (x64, AMD FX-8320E), правильная версия библиотеки устанавливается только принудительно, нужно править CMD.
2. Сжимается изображение до квадрата с потерей соотношений (на "длинных" рабочих полях), лучше его либо пропорционально уменьшать, либо обрезать (либо делать и то и другое).

**Comment by kov-serg** [comment]
Не могли бы прислать файл env.txt которые получиться после команды

set > env.txt

Да с пропорциями есть косяк, сегодня посмотрю.

**Comment by TRaMeLL** [comment]
[env.txt](https://github.com/kov-serg/ai-extension/files/4676320/env.txt)

**Comment by kov-serg** [comment]
поправил скрипты установки, теперь должно правильно определять разрядность

**Comment by TRaMeLL** [comment]
Проверил, да, теперь определяет правильно.

**Comment by kov-serg** [comment]
Поправил пропорции. Теперь должно быть как положено

**Comment by TRaMeLL** [comment]
С пропорциями нормально, единственный момент: при обычном размере значков появляется черная полоса сверху.
![scrshot1](https://user-images.githubusercontent.com/10239461/82805504-b835ee00-9eb6-11ea-84a0-d7e041f77864.png)

**Comment by kov-serg** [comment]
Сейчас посмотрю

**Comment by TRaMeLL** [comment]
Если пересохранить файлы, то всё отображается правильно. Хотел файл для примера создать и не получается, наверное, что-то с каким-то кешем.

**Comment by kov-serg** [comment]
У меня не получилось повторить
![scrshot1](https://i.imgur.com/IjwvRVH.png)

**Comment by TRaMeLL** [comment]
Да, это кеш Windows шалит. Через меню проводника поставил галку на "Всегда отображать значки, а не искизы", затем убрал, эскизы обновились нормально.
![scrshot2](https://user-images.githubusercontent.com/10239461/82809413-9fc9d180-9ebe-11ea-82dd-79954b9bb869.png)

**Comment by kov-serg** [comment]
А как вы картинки вставляете в сообщения. Я что-то не нашел в штатном диалоге.

**Comment by TRaMeLL** [comment]
Просто перетаскиваю файл на поле ввода текста, там снизу даже написано: "Attach files by dragging & dropping, selecting or pasting them."

**Comment by kov-serg** [comment]
Слона та и не заметил.
